services:
#    core.example:
#        class: CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    incolab_core.transliterator:
        class: Incolab\CoreBundle\Transliterator\Transliterator
        arguments:
            $kernel: "@kernel"
    incolab_core.bbcodeparser:
        class: Incolab\CoreBundle\BBCodeParser\BBCodeParser

    incolab_core.json_utils:
        class: Incolab\CoreBundle\JsonUtils\JsonUtils
